# production compose
version: "3.7"

services:
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile.prod
    container_name: invoicer_backend_prod
    ports:
      - 3000:3000
    env_file: .env.production
    volumes:
      - ./var:/app/var
      - ./var/out:/app/var/out

  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile.prod
    container_name: invoicer_frontend_prod
    ports:
      - 8080:8080
    environment:
      - VUE_APP_ENDPOINT=http://localhost:3000
      - VUE_APP_LOCALE=de-DE
