# development compose
version: "3.7"

services:
  backend:
    build:
      context: src/backend
      dockerfile: Dockerfile.dev
    container_name: invoicer_backend_dev
    environment:
      - "HOME=/go"
    user: "1000:1000"
    ports:
      - 3000:3000
    env_file: .env.local
    volumes:
      - ./src/backend/src:/go/src/app
      - ./var:/go/src/app/var

  frontend:
    build:
      context: src/frontend
      dockerfile: Dockerfile.dev
    container_name: invoicer_frontend_dev
    user: "1000:1000"
    ports:
      - 8080:8080
    environment:
      - VUE_APP_ENDPOINT=http://localhost:3000
      - VUE_APP_LOCALE=de-DE
    volumes:
      - ./src/frontend/src:/app
      - /app/node_modules
