#!/bin/bash
if [ $# -eq 0 ]; then
    echo "Usage: $0 [dev|prod] [args]"
    exit 1
fi

case "$1" in
   "dev") docker-compose -f docker-compose.dev.yml up $2;;
   "prod") docker-compose -f docker-compose.prod.yml up $2;;
   *) echo "No usable target"
esac
